services:
  postgres:
    container_name: postgres
    image: postgres
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    restart: always
    environment:
      POSTGRES_DB: testdb
      # POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./local-data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.0.1
    extra_hosts: ['host.docker.internal:host-gateway']
    command:
      - --enable-feature=exemplar-storage
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - prometheus:/prometheus
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
volumes:
  prometheus:
    driver: local