spring.application.name=beer-rating-service

server.port=8082

# Observability
management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.step=10s
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true
management.tracing.sampling.probability=1.0

# Database
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:beerrating}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:password}

spring.jpa.open-in-view=false

# Feign
spring.cloud.openfeign.client.config.beer.url=http://localhost:8081
spring.cloud.openfeign.client.config.beer.connect-timeout=100
spring.cloud.openfeign.client.config.beer.read-timeout=5000