spring.application.name=beer-service

# Observability
management.endpoints.web.exposure.include=*
management.prometheus.metrics.export.step=10s
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles-histogram.http.client.requests=true
management.tracing.sampling.probability=1.0

# Database
spring.datasource.url=jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:beers}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:password}

spring.jpa.open-in-view=false