CREATE TABLE beer
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)     NOT NULL,
    description VARCHAR(1000),
    origin      VARCHAR(255),
    abv         DOUBLE PRECISION NOT NULL,
    image_url   VARCHAR(255)
);

INSERT INTO beer (name, description, origin, abv, image_url)
VALUES ('Carlsberg',
        'Carlsberg je pasterizovano, svijetlo pivo, prvi put proizvedeno 1904. godine. Dio je danskog kulturnog nasleđa i predstavlja idealan napitak za gašenje žeđi. Iskusite harmoničnu ravnotežu između prijatne gorčine i slatkoće jabuka, dok konzumirate ovo pivo svetlo zlatne boje i bogate pjene. Miris i aromu piva čine mješavina bora, lješnika i kiseljaka.',
        'Danska',
        5,
        'https://www.carlsbergbosnia.ba/media/e4ubqnm0/microsoftteams-image-10.png?height=570&mode=max');

INSERT INTO beer (name, description, origin, abv, image_url)
VALUES ('Tuborg Green',
        'Priča o Tuborgu počinje davne 1880. godine, kada je u pivari, u blizini Kopenhagena, proizvedena prva boca ovog piva, koje je odmah postalo omiljeno među Dancima. Tuborg je pasterizovano, svijetlo lager pivo, dobijeno procesom donje fermentacije, kuvanjem blago pečenog svetlog slada. Ima prepoznatljiv blag i osvežavajući ukus, koje prate aroma cvijeća i žitarica.',
        'Danska',
        4.6,
        'https://www.carlsbergbosnia.ba/media/vrejz3si/global_march17-tuborg-green.png?height=570&mode=max');

INSERT INTO beer (name, description, origin, abv, image_url)
VALUES ('Kronenbourg 1664 Blanc',
        'Kronenbourg 1664  Blanc je svjetlo, pasterizirano, mutno pšenično pivo sa aromom karamela, narančine kore i korijandera i sadrži 5% alkohola. To je najprodavanije francusko pivo na svijetu i vođa na tržištu među premium pivima. Nazvano je prema godini kada je porodica Hat, osnivač Kronenbourga, počela proizvoditi za komercijalnu upotrebu. Kronenbourg je peti najstariji pivski brend na svijetu koji još uvijek postoji.',
        'Francuska',
        5,
        'https://www.carlsbergbosnia.ba/media/frmm4kii/1664_sapphire_blanc_bottle_33cl_wet_lr_rgb.png?height=570&mode=max');